<a href="https://colab.research.google.com/github/kanchan745/NumPy-Revision/blob/main/Numpy_array_properties.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#How to check shape , size and type of array

In [3]:
import numpy as np


**Shape of an array.**

In [4]:
#check how many rows and column in an array : give int no.

#use it when we 've multi dimension data

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d.shape)

#give output(2-rows , 3- columns)

(2, 3)


# Size attribute : give total no. of elements

In [5]:
#use when we 've huge data
arr = np.array([[10,20,30],[40,50,60]])
print(arr.size)

6


# ndim : attribute with the help , we can check no. of dimensions


In [8]:

arr_1d = np.array( [1,2,3])
arr_2d = np.array([[5,6,7],[4,5,6]])
arr_3d = np.array([[[8,9],[10,11],[6,12],[5,75]]])

print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)



1
2
3


In [10]:
arr = np.array([10,20,30.5,40])
#to check the type of data
print(arr.dtype)

float64


#conversion of data inside array


In [13]:
#arr.astype()
arr = np.array([1.2,2.5,3.8])
print(arr.dtype)
int_arr = arr.astype(int)
print(int_arr.dtype)
print(int_arr)

float64
int64
[1 2 3]


Mathematical operation : without using loops



In [16]:
arr =np.array([10,20,30])
print(arr +5)
print(arr *2)
print(arr**2)

[15 25 35]
[20 40 60]
[100 400 900]


**Aggregation function**

#To find summary or summarise data.  ex : average products from data

np.sum(array) -> add all elements
np.mean(array) -> calculate average
np.min(array) -> calculate smallest value in an array
np.std(array) -> To calculate standard deviation
np.var(array) -> To calculate variance
These are the some functions...






In [17]:
arr = np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))

150
30.0
10
14.142135623730951
200.0
